### ISSUE TITLE
Unprovided export error with Vite SSR

### ISSUE THREAD

**Issue by knpwrs** [solidjs/vite-plugin-solid#40]
### Describe the bug

When attempting to use `solid-app-router` with vite's SSR mode, vite complains that `solid-js/web` doesn't have an export named `effect`. Indeed, there are only two export statements from the `solid-js/web` es module and neither of them contain `effect`:

```ts
export { ErrorBoundary, For, Index, Match, Show, Suspense, SuspenseList, Switch, createComponent, mergeProps } from 'solid-js';
// ...
export { Assets, Dynamic, HydrationScript, NoHydration, Portal, escape, generateHydrationScript, getHydrationKey, isServer, pipeToNodeWritable, pipeToWritable, renderToStream, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrAttribute, ssrClassList, ssrHydrationKey, ssrSpread, ssrStyle };
```

I wasn't sure if I should open this bug here so that `solid-js/web` could export `effect` or if I should open over at `solid-app-router` so it could grab the export from a different location.

### Your Example Website or App

https://github.com/fastify/fastify-vite/tree/967be02cd66539b3cf70dc9df59b5c0af2c0f853/examples/solid-hydration

### Steps to Reproduce the Bug or Issue

1. Attempt to run example provided
2. Get the following error:

```
> NODE_ENV=development ts-node server.ts

3:04:21 PM [vite] Error when evaluating SSR module /base.tsx:
file://.../node_modules/solid-app-router/dist/index.js:1
import { isServer, template, createComponent as createComponent$1, mergeProps, spread, insert, effect, setAttribute } from 'solid-js/web';
                                                                                               ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at async nodeImport .../node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59403:21)
    at async eval (/base.tsx:7:31)
    at async instantiateModule (.../node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59333:9)
3:04:21 PM [vite] Error when evaluating SSR module .../client/index.ts:
.../node_modules/solid-app-router/dist/index.js:1
import { isServer, template, createComponent as createComponent$1, mergeProps, spread, insert, effect, setAttribute } from 'solid-js/web';
                                                                                               ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at async nodeImport (.../node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59403:21)
    at async eval (/base.tsx:7:31)
    at async instantiateModule (.../node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59333:9)
.../node_modules/solid-app-router/dist/index.js:1
import { isServer, template, createComponent as createComponent$1, mergeProps, spread, insert, effect, setAttribute } from 'solid-js/web';
                                                                                               ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at async nodeImport (.../node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59403:21)
    at async eval (/base.tsx:7:31)
    at async instantiateModule (.../node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59333:9)
zsh: exit 1     npm run dev
```

### Expected behavior

`solid-app-router` should only import things from `solid-js/web` that actually exist.

### Platform

- OS: macOS
- Browser: n/a
- Version: 1.4.3

**Comment by knpwrs** [comment]
This appears to have been user error on my part but it seems like there still might be an action item to come out of this issue? Feel free to close if the issue isn't relevant to anything anymore.

**Comment by ryansolid** [comment]
We have taken approaches for autodetection. Simple cases like the router are fixed now. And we continuing to improve it. Thank you.
