### ISSUE TITLE
Get "Couldn't find package.json for " log message when dependecy is pnpm workspace package

### ISSUE THREAD

**Issue by hackwaly** [solidjs/vite-plugin-solid#58]
```
Couldn't find package.json for eslint-config-custom Error: Cannot find module 'eslint-config-custom'
Require stack:
- /Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite-plugin-solid@2.3.7_solid-js@1.5.6+vite@3.1.3/node_modules/vite-plugin-solid/dist/cjs/index.cjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite-plugin-solid@2.3.7_solid-js@1.5.6+vite@3.1.3/node_modules/vite-plugin-solid/dist/cjs/index.cjs:59:42
    at Array.map (<anonymous>)
    at getSolidDeps (/Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite-plugin-solid@2.3.7_solid-js@1.5.6+vite@3.1.3/node_modules/vite-plugin-solid/dist/cjs/index.cjs:54:21)
    at config (/Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite-plugin-solid@2.3.7_solid-js@1.5.6+vite@3.1.3/node_modules/vite-plugin-solid/dist/cjs/index.cjs:104:25)
    at runConfigHook (file:///Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63532:31)
    at resolveConfig (file:///Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63047:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createServer (file:///Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:62063:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/yuxiang/Work/fe-app-web-v2/node_modules/.pnpm/vite-plugin-solid@2.3.7_solid-js@1.5.6+vite@3.1.3/node_modules/vite-plugin-solid/dist/cjs/index.cjs'
  ]
}
```

package.json
```json
{
  "private": true,
  "scripts": {
    "dev": "vite"
  },
  "devDependencies": {
    "vite": "^3.1.3",
    "vite-plugin-solid": "^2.3.7",
    "eslint-config-custom": "workspace:^1.0.0",
    "tsconfig": "workspace:^1.0.0"
  },
  "dependencies": {
    "solid-js": "^1.5.6"
  }
}

```

**Comment by carere** [comment]
I got the exact same issue, don't understand why. Everything worked properly few days ago

**Comment by m4rvr** [comment]
Happens for me too. There was 2.3.8 released but this doesn't seem to fix it?

**Comment by ryansolid** [comment]
To be fair this error logging shouldn't affect your build at all. It's supposed to be just extra functionality that can be ignored and just logged. That being said yeah I believe this should improve things as it was using the wrong relative path for resolution. Thanks @juanrgm
